name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: wasm-canvas

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-dev libwayland-dev libx11-dev libxrandr-dev libxi-dev libxcursor-dev libxinerama-dev
      - run: cargo build --release
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/${{ env.BINARY_NAME }}
          generate_release_notes: true

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - run: cargo build --release
      - name: Package
        shell: bash
        run: 7z a ${{ env.BINARY_NAME }}-windows.zip ./target/release/${{ env.BINARY_NAME }}.exe
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.BINARY_NAME }}-windows.zip

  build-macos-arm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - run: cargo build --release
      - name: Package
        run: tar czf ${{ env.BINARY_NAME }}-macos-aarch64.tar.gz -C target/release ${{ env.BINARY_NAME }}
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.BINARY_NAME }}-macos-aarch64.tar.gz
